# Generated by Django 5.2.12 on 2026-04-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_first_name_customer_given_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='given_name',
            new_name='first_name',
        ),
    ]
