# Generated by Django 5.2.12 on 2026-04-01 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_given_name_customer_first_name'),
    ]

    operations = [
        migrations.RunSQL("""
            INSERT INTO store_collection (title)
            VALUES ('collection 1')
        """, """
            DELETE FROM store_collection WHERE title = 'collection 1'
        """)
    ]
